### ISSUE TITLE
Beautify the currently ugly method for mass-inserts into the AvailabilitiesCollection

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#102]
There are a lot of loops and stuff. Would be nice if sb could make this better. There is potential ;)

**Comment by boredland** [comment]
Additionally: We decided that each chunk and its repetitions should have a common familiyId, not like it is now: all chunks and their repetitions. If you've questions regarding that, please ask!

**Comment by tobirohrer** [comment]
Habe die Insert Methode neu geschrieben. Jetzt funktioniert repeat until mit dem definiertem repeat intervall.

**Comment by tobirohrer** [comment]
die common "familyID + Uhrzeit" ergibt sowas wie eine "Chunk&its repitations ID" .
