### ISSUE TITLE
Make UI great again

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#103]
UI umbauen, damit das Bootstrap-Paper Theme konsequent eingehalten wird
Erklärungstexte ergänzen

**Comment by VERGiL1202** [comment]
Dialogtexte sind jetzt einheitlich in allen Dialogen.
Buttons sind jetzt einheitlich und haben passende Symbole.
Appointment-Seite ist jetzt schick.

**Comment by boredland** [comment]
Hr. Alekseev wird begeistert sein :D

**Comment by VERGiL1202** [comment]
Wollen wir den Namen eigentlich in FRA-UAS Kalender abändern? Die Landingpage sagt ja schon FRA-UAS Kalender. Muss natürlich auch an anderen Stellen geändert werden, aber Strg+Shift+F hilft ja. (z.B. in den Mails)
