### ISSUE TITLE
Delete this and all future unbooked availabilities of the family

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#104]
Could be activated by a boolean checkbox in the delete-modal-window.

**Comment by tobirohrer** [comment]
zum löschen: entweder man kann anhand der family id löschen, dann wird alles gelöscht. Oder man kann FamilyID + Uhrzeit zusammen nehmen, dann wird eine "Chuckfamilie" gelöscht.

**Comment by boredland** [comment]
Hat von euch wer schon herausgefunden, wie man serverseitig Daten aus einer anderen Collection bekommt?

**Comment by michelmeinmichel** [comment]
done

**Comment by michelmeinmichel** [comment]
bisher nur für reserved . wir speichern alle reservierten termine in einem Array zwischen, löschen dann alles , und inserten dann wieder den array in die db

**Comment by boredland** [comment]
Ich denke da ist ein refactoring nötig, da das mit dem array käs ist. http://blog.cheesemaking.com/wp-content/uploads/2012/12/ready1.jpg

**Comment by boredland** [comment]
https://github.com/boredland/MeteorKalender/tree/better_removals

**Comment by boredland** [comment]
https://github.com/boredland/MeteorKalender/tree/better_removals

**Comment by tobirohrer** [comment]
implementiert, funktioniert. Alle unbooked availabilities werden gelöscht, nicht nur die in der Vergangenheit
