### ISSUE TITLE
Drop all future availabilities

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#105]
Add a button and the functionality to drop all future availabilities to the availabilities overview.

**Comment by michelmeinmichel** [comment]
Button ist implementiert

**Comment by boredland** [comment]
"future", availabilities != appointments

**Comment by michelmeinmichel** [comment]
done

**Comment by michelmeinmichel** [comment]
bisher nur für reserved . wir speichern alle reservierten termine in einem Array zwischen, löschen dann alles , und inserten dann wieder den array in die db

**Comment by boredland** [comment]
Habe euch das mal etwas vernünftiger gemacht, ohne array etc. Wenn ihr nichts entdeckt, was an der Methode schlechter ist, würde ich vorschlagen, dass ihr #104 noch mal macht (außerdem ist der Methodenname nicht korrekt gecamelcased).
