### ISSUE TITLE
Test User automatisch anlegen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#108]
Es soll ein Test User angelegt werden, welcher nicht aus der Datenbank gelöscht wird.

**Comment by jSchip** [comment]
Es wird jetzt ein testuser erstellt mit diesen daten:
            email: "testuser@stud.fra-uas.de",
            password: "testpass",
            profile: {name: "testname"}

Die email ist aber unverifiziert, weiss nicht so recht wie man das machen soll.

**Comment by boredland** [comment]
Fixed in https://github.com/boredland/MeteorKalender/commit/ac5574c1a58affba9091dc3f215de9040c80b4b7
