### ISSUE TITLE
Das Published-Häkchen soll in der Kalenderübersicht gesetzt werden können

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#110]
Das published-Feld eines Kalenders soll durch eine checkbox dargestellt werden. Diese soll direkt in der Kalenderübersicht editiert werden können.

**Comment by boredland** [comment]
Glaube für die Funktionalität, die Hr. Alekseev in der Tabelle haben möchte, gibt es ein gutes bootstrap-paket. Vielleicht wäre das eine gute Idee für einen Feature-Branch: von der handgebauten tabelle zu einer automatisch generierten umstellen: http://vitalets.github.io/x-editable/
Das Meteorpaket dazu wäre: https://github.com/nate-strauser/meteor-x-editable-bootstrap
