### ISSUE TITLE
Falsche Darstellung der Availibility-Kalender-Zuordnung in den Private-Kalendern

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#111]
Aktuell werden alle Availabilities auf der Appointment Seite demselben Kalender zugeordnet. Eigentlich sollen sie dem Kalender zugeordnet werden, welcher bei ihrer Erstellung ausgewählt wurde.

**Comment by boredland** [comment]
Fixed in 41c6a37 - feedback welcome.
