### ISSUE TITLE
APK file konfigurieren damit die App sich mit dem Server verbindet

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#112]

**Comment by tobirohrer** [comment]
App mit:
- URL ohne Port angabegebaut, kein Erfolg.
- IP und Port, kein Erfolg.

Kein Erfolg heißt das sich das APK nicht mit dem Server verbindet...

**Comment by boredland** [comment]
Gibt es eine Möglichkeit dieses Bundle vom Server zu holen, so, wie es die App auch tun würde? So könnten wir ggf. vielleicht debuggen, ob in dem Paket eine falsche Adresse angegeben ist...

**Comment by tobirohrer** [comment]
https://github.com/meteor/meteor/issues/3698 

Die Umgebungsvariablen "DDP_DEFAULT_CONNECTION_URL" and "ROOT_URL"  auf die Server Adresse setzen, anschließend sollte es funktionierne.... 

@boredland: Kannst du die beiden Variablen bitte auf dem prod Server setzen?

**Comment by boredland** [comment]
Die ROOT_URL war eh schon die ganze Zeit gesetzt, da wir hinter einem reverse-proxy sind und Meteor desh. ja eben nicht einfach nach localhost:3000 ausliefern kann.
Muss es für die DDP_DEFAULT_CONNECTION_URL nicht dann DDP_DEFAULT_CONNECTION_URL=https://domain:443 sein?

**Comment by boredland** [comment]
Habe ich so gesetzt: https://github.com/boredland/MeteorKalender/commit/eeafd5db59c470b3a139b1d807faa0decbc11597

Weißt du, wie man dieses meteor runtime-config ausgeben kann, so wie es die leute teils in der github-issue machen?

**Comment by boredland** [comment]
Der header wird nun von nginx vollständige empfängeragnostisch gesetzt. Nicht toll, aber alle apks sollten laufen.
