### ISSUE TITLE
Löschen eines Kalenders verhindert Rendering der Ansichten, auf denen der KalenderName ausgewertet wird

### ISSUE THREAD

**Issue by VERGiL1202** [boredland/MeteorKalender#129]
Wenn ein Kalender gelöscht wird, werden alle Availabilities gelöscht. Es sollten jedoch nur die Availabilities des jeweiligen Kalenders gelöscht werden.

Reproduzierbar mit:
1. Kalender1 und Kalender 2erstellen
2. Availabilities für Kalender1 und Kalender2 erstellen
2. Kalender1 oder Kalender2 löschen.
4. Es sind nun keine Availabilities mehr vorhanden.

**Comment by boredland** [comment]
Nein, tut es nicht. In der Datenbank sind die Daten noch vorhanden, der "Fehler" besteht darin, dass die Datengewinnung für die Kalenderansicht nicht funktioniert, da zu vielen Availibilities nur keine Kalenderdaten gefunden werden.

**Comment by boredland** [comment]
Die Issue hatte ich sogar schon geahnt, desh. gibt es #100

**Comment by boredland** [comment]
PS.: Könnte natürlich ein workaround basteln, damit das nicht mehr das rendern blockiert, aber soweit ich weiß soll es ja schlichtweg nicht mehr möglich sein die zu löschen.
