### ISSUE TITLE
Fehlermeldung beim Buchen ausgeben, falls keine E-mail angegeben wird

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#132]
In der Buchungsansicht soll eine kurzte Fehlermeldung angegeben werden, falls keine E-mail Adresse angegeben wird.

**Comment by boredland** [comment]
Kannst du sagen, ob das nicht bereits mit https://github.com/boredland/MeteorKalender/commit/58059e95e669568ea6fc7a721118ed3e9a2b4ac3 gefixt wurde?

**Comment by SezenGuenes** [comment]
ja! stimmt, das reicht schon aus
