### ISSUE TITLE
Back Button in verschiedenen Formularen hinzufügen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#135]
In mehrerern Formularen müssen noch Cancel-Buttons hinzugefügt werden. 
Betroffen sind folgende Seiten:
- Seite zum Buchen von Terminen
- Unterseite einer Buchung

**Comment by VERGiL1202** [comment]
Bitte dafür gleich die Klasse btn-default setzen, dann passts auch gut ins Paper-Theme rein.

**Comment by boredland** [comment]
Da "cancel" als Wort ja auch für die Stornierung von Availabilities Verwendung findet, würde ich da eher für "back" oder so plädieren.
