### ISSUE TITLE
Meteor Sicherheitslücken prüfen und schließen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#138]

**Comment by boredland** [comment]
@jSchip hast du noch den Link mit diesen typischen Fehlern, die man beim Meteor-Programmieren macht?

**Comment by jSchip** [comment]
Das war das was ich meinte:
https://guide.meteor.com/security.html

**Comment by boredland** [comment]
Habe das Dokument entdeckt, das ich meinte:
https://dweldon.silvrback.com/common-mistakes

**Comment by tobirohrer** [comment]
Zusammenfassung bzgl. der ToDos: 

1.) Avoid/Deny für  Collecitons spezifizieren. Für die Calendar und Availabilities collection darf vom client aus update remove und insert ausgeführt werden. Keine weitere Einschränkung.
2.) Checks für Argumente die an Methoden übergeben werden. IDs werden bereits auf Datentyp String geprüft. Weitere Checks werden eingebaut.
3.) userID nicht als Argument übergeben. Ist nur in wenigen Methoden eingebaut. Wird morgen entweder rausgenommen, oder mit einem Check userID = this.UserID gesichert. 
4.) Rate limit: Höchstens 5 Anfragen pro Sekunde pro Collection einstellen.
5.) Felder von Publikationen einschränken.

**Comment by boredland** [comment]
Bzgl. 5. habe ich an einigen Stellen an denen es mir sinnig erschien schon auf genau das eingeschränkt, was ich dann brauchte. Oder meinst du man sollte es auch für eingeloggte user weiter einschränken?

**Comment by tobirohrer** [comment]
Punkt 4 und 2 sind eingebaut.
1,3  wurde geprüft und ist bei uns so wie es implementiert ist ok.
5 ist nur notwendig wenn man secret fields in den Collections hat und diese nicht an den Client publizieren will. Soweit ich weiß haben wir das nicht und muss somit auch nicht eingebaut werden.
