### ISSUE TITLE
Move the left-hand navigation to the top

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#143]

**Comment by VERGiL1202** [comment]
Done. Template vom left-menu ist aktuell noch drin. Soll das direkt raus geschmissen werden? Iron Router schmeißt mir Sachen um die Ohren, wenn ichs raus nehme.

**Comment by boredland** [comment]
Wäre dafür das rauszuwerfen, wenn danach noch alles lädt. Um die Fehlermeldungen kann ich mich kümmern.
