### ISSUE TITLE
Remove calendar including its unbooked availabilities

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#146]
And give some output to the user if he cant remove because there are booked availabilities inside the calendar.

**Comment by boredland** [comment]
And move booked events to the default calendar.

**Comment by tobirohrer** [comment]
Funktion für Löschen von Availabilities zur gleichen Zeit geschrieben. Commit 1be4489a65f638f2f079f12de5cf1a30986c94c2

**Comment by boredland** [comment]
Depends on #165

**Comment by boredland** [comment]
#165 ist erledigt.

**Comment by boredland** [comment]
Wenn ich das richtig verstanden habe, dann hat Alekseev das heute für invalid erklärt. Falls du das anders siehst, schiebs zurück.
