### ISSUE TITLE
Registrieren von Dozenten

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#15]
Ein Dozent soll sich registrieren könnnen.

Aktzeptanzkriterien:
- Ein Dozent soll sich mit Email-Adresse , Name und Passwort registrieren können
- seine Daten werden gespeichert
- Er bekommt eine Erfolgsmeldung und eine Bestätigungsmail an die angegebene Adresse
- Das Ganze soll lokal präsentiert werden

**Comment by boredland** [comment]
Siehe #32. Einzig das mit der Mail müsste man dann noch machen: die Funktionalität ist schon da. Wenn wer die Zugangsdaten braucht für einen SMTP-Server, sagt bescheid. Darf man halt nicht pushen ;)

**Comment by boredland** [comment]
Funktionierende Version ist deployed auf Heroku. Deployment auf dem FH-Server funtkioniert nicht bisher.
