### ISSUE TITLE
Texte in der Applikation anpassen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#154]
Die Beschreibungstexte der verschiedenen Löschfuntionen für Availabilities müssen überarbeitet werden.
Ebenfalls ist ein komplettes Review aller Texte notwendig. Anpassung erfolgt anschließend.

**Comment by boredland** [comment]
Im Branch "better_removals" habe ich eine etwas andere Herangehensweise (in Form von Fragen). Vielleicht versteht es so ein User.

**Comment by VERGiL1202** [comment]
done
