### ISSUE TITLE
Delete Availability and Repetitions

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#155]
Die Funktion zum Löschen einer Availability und all ihrer Wiederholungen zur selben Zeit muss noch implementiert werden.

**Comment by boredland** [comment]
Schaut euch das mal im Branch "better removals" an. Ich habe dort folgende Mögllichkeiten vorgesehen und auch mit Modalfenstern verknüpft:
"Family ab diesem"
"Family ab jetzt"
"Repetitions ab diesem"
"Repetitions ab jetzt"
"Nur die aktuelle löschen"
