### ISSUE TITLE
Log in von Dozenten

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#16]
Prüfen ob der Durch meteor-Kitchen erstellte Login den Anforderungen entspricht und funktioniert.

**Comment by boredland** [comment]
Siehe #32: ist bereits in der MeteorKitchen enthalten, die ich im Demo-Branch gepostet habe. Müsste halt wer noch mal im Master machen, dann kann man den Demo-Branch auch löschen.

**Comment by furkan92** [comment]
Das ist doch jetzt auch in Master. Also ich denke mal dass wir mit dem Thema durch sind.
