### ISSUE TITLE
Add a FAQ-Page (public)

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#175]
And fill it with the most common questions

**Comment by michelmeinmichel** [comment]
jan brauchst du noch hilfe beim erstellen oder hast du alles im griff

**Comment by VERGiL1202** [comment]
Weil hier public im header steht: sollte die nicht eher für den private bereich sein?

**Comment by jSchip** [comment]
Ok anscheinend brauch ich da doch etwas Hilfe.

**Comment by boredland** [comment]
Bei was genau?

**Comment by jSchip** [comment]
Ich war so weit, dass man nur noch die faq Seite füllen musste, als ich bemerkt hab dass die Hälfte der anwendung nicht funktioniert, selbst nachdem ich meine aenderungen zurueckgenommen hab. Bis jetzt hat nichts geholfen. Ich versuch mal das ganze Projekt bei mir neu anzulegen.

**Comment by boredland** [comment]
Ist aber nicht der Fehler, den alle anderen auch hatten, dass man Seiten auf denen Formulare sind nicht aufrufen kann?

**Comment by jSchip** [comment]
Hmm kann sein. Wie behebt man den?

**Comment by VERGiL1202** [comment]
git submodule update --init --recursive

**Comment by VERGiL1202** [comment]
Bitte überarbeitet auch nochmal den Content etwas...
Und von der View her wäre so ein Accordion schön:
http://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-accordion.php

**Comment by michelmeinmichel** [comment]
Jo accordion is schon geplant werd ich morgen oder fr noch mal rein machen , noch Ideen für den Content?

**Comment by VERGiL1202** [comment]
Einige Schreibweisen überarbeiten, z.B.
Definitely yes !.
Fra-UAS

Und außerdem fehlt halt noch vieles, wie z.B. die app oder "how do I cancel..." oder die "übersichtsseite"

**Comment by michelmeinmichel** [comment]
so accordion is drin. Inhalte müssen noch überarbeitet werden . Jan willst du noch mal drüber gehen ?
