### ISSUE TITLE
API für "Verfügbarkeit Collection" in der MongoDB

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#18]
Bereitstellen einer Api für die Termin Collection der MongoDB. Im Detail: 
-Definition von Funktionen, um in die Datenbank zu schreiben. 
-Überprüfung eines Schemas mittels "Checks".

**Comment by tobirohrer** [comment]
Reminder: entfernen des "insecure" Paketes nachdem die "MongoDB Collection API" fertig gestellt ist. Inserts mit <MongoDBName>.insert()  düfren dann nicht mehr funktionieren..

**Comment by tobirohrer** [comment]
Reminder2: entfernen des "autopublish" Paketes.
