### ISSUE TITLE
Erstellen einer initialen Eingabemaske für Verfügbarkeiten

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#20]
Erstellen einer Maske für Verfügbarkeiten, die in verschiedene Kategorien eingeteilt werden können.

ToDo:
- Button zum hinzufügen einer neuen Verfügbarkeit anlegen
- Speichern Button in Formular speichert den Termin in der Collection ab

**Comment by boredland** [comment]
Vorschlag für die Eingabemaske:
https://docs.google.com/spreadsheets/d/1aLIi5PMp7Jh5-VokZXCTIGbjOfRQYv5AlgX62BRkolY/edit?usp=sharing

**Comment by boredland** [comment]
Außerdem ist die Voraussetzung, dass #59 abgeschlossen ist. Und bereits die freizugebenden Kalender erstellt werden können.

**Comment by boredland** [comment]
Habe das mal wieder auf in progess geschoben, da das ja lange noch nicht abgeschlossen ist, kann aber erst fertig gemacht werden, wenn die Datenbankanbindung so halbwegs finalisiert ist.
