### ISSUE TITLE
Lizenz für das Projekt hinterlegen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#205]

**Comment by AlmedinTA** [comment]
Brauchen wir die Lizenz für "Commercial-use" oder "Non-Commercial-use"?

**Comment by boredland** [comment]
Ich weiß nicht. War das nicht der Task von @marshmallow92, die zu vergleichen und morgen eine Art Entscheidungsvorlage zu liefern?

**Comment by AlmedinTA** [comment]
Keine Ahnung. Naja ich vergleiche die  beiden Möglichkeiten und wir können uns dann Morgen  anhand einer Entscheidungsvorlage entscheiden.

**Comment by boredland** [comment]
Das sind nicht zwei Möglichkeiten. Es gibt zahllose verschiedene kommerzielle und unkommerzielle Modelle. War das mit @marshmallow92 abgesprochen, dass @HitBox47 sie unassigned und dich assigned @AlmedinTA ?

**Comment by HitBox47** [comment]
sie hat sich selbst unassigned

**Comment by boredland** [comment]
kk
