### ISSUE TITLE
Produktions-Apk verlinken

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#209]

**Comment by boredland** [comment]
Und guten ort dafür überlegen. Der link ist: https://github.com/boredland/MeteorKalender/raw/test_cors/.app/android/dateyourprof-unsigned_prod.apk

**Comment by VERGiL1202** [comment]
Link hat sich ja geändert, weil jetzt unter releases.
Hab mir die master002 gezogen und in /public/apk gesteckt.
Auf der Landingpage wird jetzt geprüft, ob das Gerät Android verwendet. Wenn ja, wird eine kleine Zeile mit APK Download unter der Navi eingeblendet.

In der App selbst erscheint diese Zeile nicht, obwohl es ein Android Device ist. Ist ja auch sinnvoll so.
