### ISSUE TITLE
Veröffentlichen von gespeicherten Kalendern

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#21]
- Beim Erstellen des Kalenders wird ein Link zu diesem generiert.
- Der Link soll beim betrachten der Kalender angezeigt werden

**Comment by boredland** [comment]
Link wird jetzt auch als Link angezeigt. Letzteres halte ich aktuell für Käse und finds auch komisch das in eine Issue zu hauen. Und "beim betrachten" meint hoffentlich beim anzeigen der Kalenderübersicht, oder nicht?
