### ISSUE TITLE
Bestätigungsmails bei Terminbuchung schicken

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#23]
Der Student sollte eine E-Mail an seiner Email-Adresse erhalten, damit er seine Buchung bestätigen kann

**Comment by tobirohrer** [comment]
Ich werde eine Methode zur verfügung stellen mit der man mit der Availabilities ID ein Booking auf Confirmed setzen kann.

**Comment by boredland** [comment]
Jonas erstellt Dings mit ironrouter.

**Comment by boredland** [comment]
Dings erstellt: https://github.com/boredland/MeteorKalender/commit/bed5b7cdf56f2d0844c2e87108060049333b25ee

**Comment by boredland** [comment]
Es muss geklärt werden, wieso die Methode in der verify_booking.js doppelt ausgeführt wird...
