### ISSUE TITLE
Registrieren von Dozenten auf dem Server

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#31]
Das Registrieren von Dozenten soll auf dem Server laufen. Dabei ist das Senden der Bestätigungsmail noch nicht notwendig. Jedes Teammitglied soll sich testweise als Dozent registrieren.

**Comment by boredland** [comment]
Was ist mit "auf dem Server laufen" gemeint?

**Comment by boredland** [comment]
Wenn ich richtig verstanden habe, dann gibts das doch schon, oder?
