### ISSUE TITLE
Startpunkt mit Meteor kitchen erstellen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#32]
Es soll ein initiales Projekt mit Meteor kitchen erstellt werden, welches die grundlegenden Funktionalitäten beeinhaltet. Die restlichen Funtionalitäten werden später eingefügt.

**Comment by boredland** [comment]
Man kann gleich diese KitchenJson verwenden: 
https://raw.githubusercontent.com/boredland/MeteorKalender/demo/MeteorKalender.json

**Comment by tobirohrer** [comment]
404 not found...

**Comment by boredland** [comment]
https://github.com/boredland/MeteorKalender/blob/master/MeteorKitchen.json
