### ISSUE TITLE
KalenderAPI sichten

### ISSUE THREAD

**Issue by tobirohrer** [boredland/MeteorKalender#33]
die fullcalendar api stellt kalender Funktionen für Meteor zur Verfügung.

Was kann alles damit gemacht werden? Welche Funktionalitäten stellt die API schon bereit.

**Comment by HitBox47** [comment]
Eine kurze Präsentation am Montag

**Comment by AlmedinTA** [comment]
.

**Comment by boredland** [comment]
Zur Anpassung des Fullcalender: https://fullcalendar.io/docs/display/
