### ISSUE TITLE
Test meteor "app functionality" auf Android

### ISSUE THREAD

**Issue by tobirohrer** [boredland/MeteorKalender#49]
Funktioniert das Deployment der App auf ein Android device?

**Comment by tobirohrer** [comment]
- Der Befehl "meteor add-platform android" fügt den Support für Cordova hinzu und macht die App für Android lauffähig.
- Nachdem ein Virtuelles Android Device gestartet ist kann die App mit dem Befehl "meteor run android" auf der VM gestartet werden.

Details sind im Wiki Dokumentiert.

**Comment by boredland** [comment]
Verändert das den Entwicklungsprozess oder kann man das jederzeit zur Produktion der App hinzugefügt werden?

**Comment by boredland** [comment]
https://github.com/raix/push
