### ISSUE TITLE
Registrierungsformular Email RegEx

### ISSUE THREAD

**Issue by VERGiL1202** [boredland/MeteorKalender#50]
Email Adresse muss von FRA-UAS sein.
RegEx Pattern ist zu prüfen

**Comment by boredland** [comment]
Done. Es wird auf folgende Patterns geprüft: Wenn der normale Email-Filter die Eingabe akzeptiert wird gegen [xyz]@[xyz].(fra-uas|frankfurt-university|fh-frankfurt).de geprüft. Ich habe das mal gegen mein Postfach getestet: dozenten haben entweder alte Adressen @fb2.fh-frankfurt.de oder eben sonstige fb[*].fra-uas.de. frankfurt-university scheint mir jedoch auch als alias möglich. D.h. wenn wir lediglich dozenten eine Regsitrierung erlauben wollten könnten wir es mit einem pattern @fb[0-12].(fra-uas|frankfurt-university|fh-frankfurt).de sogar weiter einschränken, weiß aber nicht, inwiefern das nötig ist.
