### ISSUE TITLE
Tabellarische Übersicht aller Termine für Appointments/Availabilities Seite

### ISSUE THREAD

**Issue by VERGiL1202** [boredland/MeteorKalender#52]
Ein eingeloggter Dozent kann alle seine Termine in tabellarischer Ansicht einsehen.

Beispiel: https://fullcalendar.io/js/fullcalendar-3.0.1/demos/list-views.html

**Comment by boredland** [comment]
Wieso steht das auf "in progress". Ich halte das für Käse, solange es keine halbwegs passabel implementierte Datenstruktur gibt. Ich glaube da kommen sich tobi und andere nur in die Quere.

**Comment by boredland** [comment]
Bzw.: Bookings gibts ohnehin noch überhaupt nicht Oo. Ergibt diese Woche noch keinen Sinn...

**Comment by michelmeinmichel** [comment]
das ist jetzt erstmal soweit fertig

**Comment by boredland** [comment]
Nein, ist es nicht. Auf der Availabilites-Seite ist ja noch keine Übersicht mithilfe des fullcalendar (analog zur Appointments-Seite). Das ist copy&paste, machst dus?

**Comment by boredland** [comment]
Habe nun quch den Part nich gemacht. Und gleich noch ein paar korrekturen.

**Comment by michelmeinmichel** [comment]
ja sorry hatte ich irgenwie nicht gesehen, dass du hier die waffle kommentiert hast

**Comment by boredland** [comment]
Ja ich glaube ich bin der einzige, der die Kommentarfunktion außerhalb von Mittwochs benutzt xD
