### ISSUE TITLE
Flow-Charts erstellen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#61]
Ablaufdiagramme erstellen für folgende Themen:
- Mögliche Aktionen eines eingeloggten Users
- Buchung von Terminen

Frage:
Bestätigung von User+Dozent notwendig?
Haben Kalender oder Verfügbarkeiten einen Ort?

**Comment by Xtern77** [comment]
![studentsview](https://cloud.githubusercontent.com/assets/16243189/20340492/014cbdb0-abe2-11e6-8986-c4a123a2d0ab.png)
![loggedinuser](https://cloud.githubusercontent.com/assets/16243189/20340493/014e2682-abe2-11e6-91be-964d339dab6d.png)

**Comment by boredland** [comment]
@Xtern77 Bitte verlinke das doch hier mal noch aus Google Drive.
