### ISSUE TITLE
Eingabemaske für neue Verfügbarkeiten

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#63]
*Neue Verfügbarkeit*

Start	
Ende	
Buchung bis	
Split into intervalls of Size (minutes)	5,10,20...[total duration]
Wiederholen?	
	Intervall
	Bis [select aus Intervallen]
Kalender	"+"

**Comment by boredland** [comment]
Fast alles bis auf: Split und Intervall + Intervall bis ist drin.

**Comment by boredland** [comment]
Ist jetzt vollständig.
