### ISSUE TITLE
Auf Wording einigen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#65]
Die Vereinbarungen sind im github Wiki festzuhalten

**Comment by boredland** [comment]
Ich glaube wir hatten uns auf "Kalender" (Das was den Endnutzern freigegeben wird), "Verfügbarkeiten"/Availabilities (die Termine, die man buchen kann), "Buchungen"/Appointments für die Verfügbarkeiten mit Buchungsmerkmalen geeinigt.

**Comment by boredland** [comment]
Overview: Übersicht über Availabilities und Appointments.
