### ISSUE TITLE
Die Rolle des Admins erstellen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#68]
Admin soll Zugriff auf alle Kalender aller Benutzer haben und diese bearbeiten können.

**Comment by boredland** [comment]
Ich glaube es geht weniger um die Rolle, ein Rollenkonzept gibts in fertig (https://github.com/alanning/meteor-roles). Ich glaube es wäre eher zu überlegen entsprechende Bereiche erstmal zu erstellen, in denen man alles bearbeiten kann (alle Benutzer, Kalender und Availabilities, sowie deren Verbdindungen).

**Comment by boredland** [comment]
Könnte vielleicht der PO hier mal genau genau klären, was das Admin-Backend können soll? @Xtern77
