### ISSUE TITLE
Cancellation of bookings by professors

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#69]
Neues Modalfenster mit:
- Eingabefeld für Grund
- Zwei Buttons:
-> Cancel appointment and keep availability
-> Cancel appointment and delete availability

**Comment by boredland** [comment]
Vielleicht solle "no" ne Option sein... :D

**Comment by boredland** [comment]
Und das sollte auch nicht einfach Availabilities.remove() aufrufen, lieber eine neue Methode Availabilities.cancel(), in der wir dann die Mail verschicken, oder?

**Comment by boredland** [comment]
Ich fänds okay wenn du aktuell nur auf der konsole den inhalt der mail schreibst, die dem studenten in beiden fällen ja geschickt werden sollte. ich werde uns ne allgemeinere mail-methode schreiben, damit wir da nicht endlos codedupletten erzeugen.

**Comment by furkan92** [comment]
habe ich mir auch überlegt aber wir müssen doch trotzdem die Availability löschen deswegen habe ich die Methode benutzt

**Comment by boredland** [comment]
Ich habe ein Modalfenster hinzugefügt, in dem der Dozent einen Grund für die Absage eingeben muss und die cancel-methode so umgestaltet, dass wir die jetzt quasi überall verwenden können.
