### ISSUE TITLE
Add Min and Max to Datetimepickers

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#72]
Needs to be added here, added console outputs to prove the events get called in the correct situations. 

https://github.com/boredland/MeteorKalender/blob/test/client/views/home_private/availabilities/availabilities.js

Should be similar to: http://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

**Comment by boredland** [comment]
Mir fällt dazu noch ein, dass solche Sprechstundenzeiten Minuten, vielleicht auch Stunden umfassen, aber wohl kaum Tage. Wäre es ggf. vielleicht (in der gui) ausreichend Start + Zeitraum (Dauer) zu erheben? Ggf. hätte sich das damit eh erledigt. Vielleicht eine gute Frage an @HitBox47 und @Xtern77 ..

**Comment by tobirohrer** [comment]
Diskussion am 28.11. : Bei der Auswahl des EndDates sollte man nur eine Uhrzeit anpassen können. Es wird nie Sprechstunden über 2 Tage geben!

**Comment by VERGiL1202** [comment]
Es sollen falsch gesetzte Felder Rot markiert werden.

**Comment by boredland** [comment]
https://github.com/aldeed/meteor-autoform#manual-validation
