### ISSUE TITLE
Fix glyphicons "invalid version tag"

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#73]
The glypicons for the datetimepicker (and I guess everywhere else) are not showing up. You can check this on the availabilities-page with the javascript console. This problem is common, google it.

`availabilities:1 Failed to decode downloaded font: http://localhost:3000/fonts/glyphicons-halflings-regular.woff2
availabilities:1 OTS parsing error: invalid version tag
availabilities:1 Failed to decode downloaded font: http://localhost:3000/fonts/glyphicons-halflings-regular.woff
availabilities:1 OTS parsing error: invalid version tag
availabilities:1 Failed to decode downloaded font: http://localhost:3000/fonts/glyphicons-halflings-regular.ttf
availabilities:1 OTS parsing error: invalid version tag`

**Comment by HitBox47** [comment]
https://github.com/boredland/MeteorKalender/tree/test/client/styles/framework

**Comment by boredland** [comment]
Habe die glyphicons entfernt. Mal sehen, ob das zu Problemen führt. Sagt, wenn euch mal fehler auffallen.

**Comment by boredland** [comment]
Bisher sah das gut aus, keine weiteren Fehler.
