### ISSUE TITLE
Drop-Down Menü für eingeloggte User funktioniert nicht mehr

### ISSUE THREAD

**Issue by VERGiL1202** [boredland/MeteorKalender#75]
Fehlerdiagnose:
Der Fehler ist in commit 3ef6425.

Als zusatzinfos hätte im im angebot, dass die relevanten datei layout.js "Template.layout.events({  "click": function(event)..." nicht verändert wurde. Mein tip wäre, dass irgendwas von dem, was ich eingefügt habe damit kollidiert.

**Comment by boredland** [comment]
Also das Menü funktioniert wieder, indem twbs:bootstrap entfernt wurde. Nun scheint mir aber die Seite bei jedem klick auf "submit" neu zu laden. Da ich nicht wüsste, dass oder wo ich beim Beheben des Bugs etwas an der availabilities-seite geändert habe, schätze ich, dass der Fehler damit zusammenhängt, dass die Voraussetzungen für [aldeed:autoform-bs-datetimepicker](https://atmospherejs.com/aldeed/autoform-bs-datetimepicker) nicht mehr zutreffen. m.E. gibts da zwei variablen. Einerseits halte ich mich nicht an das unter dem Link angegebene Versionsconstraint für den tsega:bootstrap3-datetimepicker. Andererseits fehlt nun halt twbs:bootstrap. Wäre gut, wenn wer das 1. durchtestet und 2. dann hier berichtet. Wenn es nämlich so ist, wie ich befürchte und twbs:bootstrap nötig ist für autoforms bzw den Datetimepicker, dann wäre ich eher dafür sich noch mal anzusehen, ob es ne Möglichkeit gibt dieses Dropdown so umzubauen, dass es mit autoforms funktioniert. Das ist eine bei weiten sauberere implementierung der Formulare über die Datenbankconstraints, die @tobirohrer so toll angelegt hat und ich fänds deutlich cooler darauf zu bauen als jetzt wegen so eines Dropdowns auf tolle und klare Strukturen zu verzichten.

**Comment by boredland** [comment]
So. Ich denke mit der korrekten Versionsnummer und mit Verzicht auf twbs:bootstrap läufts. Wenns jemand confirmed können wir das hier schließen.
