### ISSUE TITLE
Umsetzen des Datenbank Schemas

### ISSUE THREAD

**Issue by HitBox47** [boredland/MeteorKalender#77]
#59 als MongoDB Collections umsetzen

**Comment by tobirohrer** [comment]
Diskussion am 28.11.: 
Prüfen ob: 
n:m beziehung zwischen Availabilities und Calendars umsetzen. Calendars hat ein Array mit den zugehörigen AvailabilityIDs und Availabilities hat Array mit CalendarIDs.
Oder:
Nur Availabilities hat array von Calendar IDs. Query muss die Zugehörigkeit in die Andere Richtung herstellen. 

Task: Tobi prüft was performanter bzw. gängiger ist

**Comment by tobirohrer** [comment]
#83 es wird ein Index über die CalendarIDs in der Availabilities Colleciton erstellt. Wenn Alle Availabilities in einem Calendar abgerufen werden, ist die Query mit Hilfe dieses Index schnell genug
