### ISSUE TITLE
Kommentar Syntax vorstellen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#78]
Eine kurze Vorstellung, wie Kommentare erstellt werden sollen sowie ein Wiki Eintrag.

https://dzone.com/articles/introduction-jsdoc

**Comment by boredland** [comment]
https://github.com/boredland/MeteorKalender/wiki/JSDoc-Dokumentation

**Comment by boredland** [comment]
https://www.npmjs.com/package/meteor-jsdoc
