### ISSUE TITLE
Struktur von Meteor Kitchen überprüfen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#79]
Jemand soll sich Meteor Best Practice durchlesen und überprüfen, ob der mit Meteor Kitchen generierte Code der dort beschriebenen Struktur entspricht.

**Comment by boredland** [comment]
Ich möchte diese Waffle nicht, aber glaube, dass es nicht sehr viel Aufwand wäre Bootstrap und das Flatly-Theme über Pakete einzubinden und die nichtpaketierten Dinge aus unserem Git zu löschen. Da müsste man halt ggf. sinnvolle Stylesheet-Elemente so trial-und-error mäßig behalten, das ist vmtl. die größte Arbeit daran. Ich sehe da größere Probleme auf uns zukommen, weil viele der Tollen Funktionen von Bootstrap erstmal nicht funktionieren (its a feature, ich schätze das ist die Designnote, die Kitchen dem geben wollte. Aufgefallen ists mir bspw. bei den Input addons:
https://bootswatch.com/flatly/#forms
