### ISSUE TITLE
Erstellung von Serienterminen durch insert Methode der Availabilities collection ermöglichen

### ISSUE THREAD

**Issue by tobirohrer** [boredland/MeteorKalender#81]
Wenn der Benutzer eine "Serien - Availability" erstellt soll ein Collection Eintrag für jede einzelne Availability erstellt werden. Es muss also aus den Informationen StartDatum, Enddatum, Terminlänge usw. errechnet werden, welche Availabilitier erstellt werden.

**Comment by boredland** [comment]
Funktioniert grob, viele Feinheiten sind aber *nicht* bedacht. Was aber funktioniert: es ist integriert in Struktur Maske->Schema->Transformation->Insert->Schema->Collection. So ist sichergestellt, dass wir weiter von der zentralen Generierung der Formulareigenschaften profitieren, aber auch schön weiter validieren und transformieren. Können.
