### ISSUE TITLE
Gesetzliche Feiertage berücksichtigen

### ISSUE THREAD

**Issue by boredland** [boredland/MeteorKalender#82]
http://feiertage.jarmedia.de/api/?jahr=2016&nur_land=HE&nur_daten=1&callback=hessenarray

https://docs.meteor.com/api/http.html

**Comment by VERGiL1202** [comment]
Checkbox hinzufügen: Bei wiederholten Verfügbarkeiten trotzdem anlegen

**Comment by VERGiL1202** [comment]
Methoden:
"Gib mir ein Array mit Feiertagen"
"Ist x ein Feiertag"

**Comment by SezenGuenes** [comment]
Soll eine Meldung ausgegeben werden, falls availabilities an Feiertagen nicht gebucht werden?
