### ISSUE TITLE
Index über calendarID in Availabilities collection erstellen

### ISSUE THREAD

**Issue by tobirohrer** [boredland/MeteorKalender#83]

**Comment by tobirohrer** [comment]
Bei Startup des Servers wird der Index über CalendarIT in der Availabilities Collection erstellt. Das ganze wird aus dem Code selbst raus getriggert. Habe auch auf der DB mit db.availabilities.getIndexes() kontrolliert, ob der Index erstellt wird. Funktioniert.

**Comment by boredland** [comment]
Besser hier:
`collection.js:684Uncaught Error: Can only call _ensureIndex on server collections(…)Mongo.Collection._ensureIndex @ collection.js:684(anonymous function) @ availabilitiesCollection.js:13maybeReady @ meteor.js?hash=e3f53db…:809loadingCompleted @ meteor.js?hash=e3f53db…:821`

**Comment by tobirohrer** [comment]
Die Exception wurde geworfen da der Index auf Client und Server erstellt wurde. Ist natürlich Schwachsinn, der code soll nur auf dem Server laufen. Ist jetzt angepasst und funktioniert.
