### ISSUE TITLE
Neue Seite: Editieren von Kalendern

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#85]
Neue Seite: Editieren von Kalendern
Diese öffnet sich beim Klick auf das Edit-Icon

**Comment by boredland** [comment]
Seite ist erstellt, jedoch noch leer.

**Comment by boredland** [comment]
Seite mit Formular gefüllt. Läuft.

**Comment by furkan92** [comment]
Funktioniert
