### ISSUE TITLE
Userfriendly view of availabilities and calendars

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#86]
The view of availabalities and calendar should be more userfriendly.

For example sorted availabilities.

**Comment by boredland** [comment]
They are sorted now.

**Comment by boredland** [comment]
What else is meant by that? And: Was ist das für 1 Issue?

**Comment by boredland** [comment]
Moment, war damit nicht gemeint, dass die Dinge auf Unterseiten verteilt werden? Ist das nicht doppelt?

**Comment by boredland** [comment]
Danke für die hilfreichen Antworten, ProductOwner und Scrummaster.
