### ISSUE TITLE
APK file für MeteorKalender erstellen

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#90]

**Comment by tobirohrer** [comment]
APK File erstellt, signiert und auf unser Repo gepushed. Es liegt im Projekt root. Es gibt noch ein Problem mit der Verbindung zwischen APP und Server.

**Comment by tobirohrer** [comment]
https://github.com/meteor/meteor/issues/3698

--> Server muss mit Parameter --mobile-server https://test.meteorkalender.freeddns.org:443 gestartet werden. 

Sonst (Zitat):
"When the mobile app connects (to the server you specify when running meteor bundle --server), the server sends a new bundle containing its own data, including its own ip. Unless you set it with --mobile-server, this ip will be localhost:3000"
