### ISSUE TITLE
Neue Seite: Neuer Kalender hinzufügen

### ISSUE THREAD

**Issue by VERGiL1202** [boredland/MeteorKalender#91]
Impliziert das verschieben des aktuellen Codes in diese neue Seite
Ebenso muss ein Button angelegt werden: Neuer Kalender hinzufügen

**Comment by boredland** [comment]
Seite ist erstellt, jedoch noch leer.

**Comment by boredland** [comment]
Habe ich eingebaut.

**Comment by michelmeinmichel** [comment]
Den Button  schon , die Seite hab ich verschoben
