### ISSUE TITLE
Neue Seite: Neue Verfügbarkeit anlegen

### ISSUE THREAD

**Issue by VERGiL1202** [boredland/MeteorKalender#92]
Impliziert das verschieben des aktuellen Codes in diese neue Seite
Ebenso muss ein Button angelegt werden: Neue Verfügbarkeit hinzufügen

**Comment by boredland** [comment]
Seite ist erstellt, jedoch noch leer.

**Comment by boredland** [comment]
Funktioniert. Ein paar Constraints habe ich auch rein. Tricky: Datumsvergleiche sind noch immer die Pest.
