### ISSUE TITLE
Neue Seite: Editieren von Verfügbarkeiten

### ISSUE THREAD

**Issue by VERGiL1202** [boredland/MeteorKalender#93]
Es soll eine Form geben, die vorausgefüllt wird mit den Daten der Verfügbarkeit.
Wenn z.B. die Dauer verringert wird etc. muss die Logik alle bisher in der DB enthaltenen Daten aktualisieren.

**Comment by boredland** [comment]
Seite ist erstellt, jedoch noch leer.

**Comment by boredland** [comment]
Habe ich eingebaut. Kalenderbearbeitung kann jetzt analog eingebaut werden.
