### ISSUE TITLE
Eine Lösung für logging auswählen und implementieren

### ISSUE THREAD

**Issue by Xtern77** [boredland/MeteorKalender#98]
Es soll eine Lösung für das logging ausgewählt werden.

**Comment by boredland** [comment]
+ und implementieren bitteschön nicht wieder so ein Käs mit "Auswahl" wochenlang ohne Implementierung...

**Comment by boredland** [comment]
Danke @VERGiL1202 ;)

**Comment by VERGiL1202** [comment]
Implementiert mit votercircle:winston meteor paket
